version: '3.8'

services:
  backend1:
    build: .
    ports:
      - "1111:8000"
    env_file: .env
    depends_on:
      - redis

  backend2:
    build: .
    ports:
      - "2222:8000"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server
      $${REDIS_PASSWORD:+--requirepass $$REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: